#include "..\..\UI\HG_IDCS.h"
/*
    Author - HoverGuy
    © All Fucks Reserved
	Website - http://www.sunrise-production.com
*/

#define HG_WEAPONS_SHOP_DISP	  findDisplay HG_WEAPONS_SHOP_IDD
#define HG_WEAPONS_ITEM_LIST	  (HG_WEAPONS_SHOP_DISP displayCtrl HG_WEAPONS_ITEM_LIST_IDC)
#define HG_WEAPONS_ITEM_TEXT	  (HG_WEAPONS_SHOP_DISP displayCtrl HG_WEAPONS_ITEM_TEXT_IDC)
#define HG_WEAPONS_ITEM_PICTURE	  (HG_WEAPONS_SHOP_DISP displayCtrl HG_WEAPONS_ITEM_PICTURE_IDC)
#define HG_WEAPONS_ITEM_SWITCH	  (HG_WEAPONS_SHOP_DISP displayCtrl HG_WEAPONS_ITEM_SWITCH_IDC)
#define HG_WEAPONS_BUY			  (HG_WEAPONS_SHOP_DISP displayCtrl HG_WEAPONS_BUY_IDC)
#define HG_WEAPONS_MC             (HG_WEAPONS_SHOP_DISP displayCtrl HG_WEAPONS_MC_IDC)
#define HG_WEAPONS_AMOUNT         (HG_WEAPONS_SHOP_DISP displayCtrl HG_WEAPONS_AMOUNT_IDC)
#define HG_WEAPONS_ADD            (HG_WEAPONS_SHOP_DISP displayCtrl HG_WEAPONS_ADD_IDC)
#define HG_WEAPONS_SUB            (HG_WEAPONS_SHOP_DISP displayCtrl HG_WEAPONS_SUB_IDC)
#define HG_WEAPONS_TOTAL          (HG_WEAPONS_SHOP_DISP displayCtrl HG_WEAPONS_TOTAL_IDC)
